name: CI

on:
  - push
  - pull_request

jobs:
  default:
    strategy:
      matrix:
        node:
          - 18
          - 20
        os:
          # - macOS-latest
          # - windows-latest # I don't have a Windows machine to debug
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node }} with cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Type checking
        run: pnpm type-check
